package com.sys.dao;

import com.sys.entity.SysPetTest;

public interface SysPetTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_test
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long petTestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_test
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    int insert(SysPetTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_test
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    int insertSelective(SysPetTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_test
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    SysPetTest selectByPrimaryKey(Long petTestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_test
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SysPetTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_test
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    int updateByPrimaryKey(SysPetTest record);
}