package com.sys.dao;

import com.sys.entity.SysPetShowerTime;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysPetShowerTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower_time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long petShowerTimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower_time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int insert(SysPetShowerTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower_time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int insertSelective(SysPetShowerTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower_time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    SysPetShowerTime selectByPrimaryKey(Long petShowerTimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower_time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SysPetShowerTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower_time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int updateByPrimaryKey(SysPetShowerTime record);

    List<SysPetShowerTime> selectList(@Param("where") String where);
}