package com.sys.dao;

import com.sys.entity.SysPetSymptoms;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysPetSymptomsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_symptoms
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long petSymptomsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_symptoms
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int insert(SysPetSymptoms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_symptoms
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int insertSelective(SysPetSymptoms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_symptoms
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    SysPetSymptoms selectByPrimaryKey(Long petSymptomsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_symptoms
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SysPetSymptoms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_symptoms
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int updateByPrimaryKey(SysPetSymptoms record);

    List<SysPetSymptoms> selectList(@Param("where") String where);
}