package com.sys.dao;

import com.sys.entity.SysPet;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysPetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long petId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    int insert(SysPet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    int insertSelective(SysPet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    SysPet selectByPrimaryKey(Long petId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SysPet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    int updateByPrimaryKey(SysPet record);

    List<SysPet> selectList(@Param("where")String where);

    List<SysPet> selectNoneList();
}