package com.sys.dao;

import com.sys.entity.SysPetSterilizationConfig;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysPetSterilizationConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_sterilization_config
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long petSterilizationConfigId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_sterilization_config
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int insert(SysPetSterilizationConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_sterilization_config
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int insertSelective(SysPetSterilizationConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_sterilization_config
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    SysPetSterilizationConfig selectByPrimaryKey(Long petSterilizationConfigId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_sterilization_config
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SysPetSterilizationConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_sterilization_config
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int updateByPrimaryKey(SysPetSterilizationConfig record);

    List<SysPetSterilizationConfig> selectList(@Param("where") String where);
}