package com.sys.dao;

import com.sys.entity.SysPetVaccineConfig;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysPetVaccineConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine_config
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long petVaccineConfigId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine_config
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int insert(SysPetVaccineConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine_config
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int insertSelective(SysPetVaccineConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine_config
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    SysPetVaccineConfig selectByPrimaryKey(Long petVaccineConfigId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine_config
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SysPetVaccineConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine_config
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int updateByPrimaryKey(SysPetVaccineConfig record);

    List<SysPetVaccineConfig> selectList(@Param("where") String where);
}