package com.sys.dao;

import com.sys.entity.SysPetOrder;

public interface SysPetOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_order
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long petOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_order
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int insert(SysPetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_order
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int insertSelective(SysPetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_order
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    SysPetOrder selectByPrimaryKey(Long petOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_order
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SysPetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_order
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int updateByPrimaryKey(SysPetOrder record);
}