package com.sys.entity;

import java.io.Serializable;
import java.util.Date;

public class SysMemberVip implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member_vip.member_vip_id
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    private Long memberVipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member_vip.name
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member_vip.discount
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    private Integer discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member_vip.create_time
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_member_vip
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_vip.member_vip_id
     *
     * @return the value of sys_member_vip.member_vip_id
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public Long getMemberVipId() {
        return memberVipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_vip.member_vip_id
     *
     * @param memberVipId the value for sys_member_vip.member_vip_id
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public void setMemberVipId(Long memberVipId) {
        this.memberVipId = memberVipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_vip.name
     *
     * @return the value of sys_member_vip.name
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_vip.name
     *
     * @param name the value for sys_member_vip.name
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_vip.discount
     *
     * @return the value of sys_member_vip.discount
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_vip.discount
     *
     * @param discount the value for sys_member_vip.discount
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_vip.create_time
     *
     * @return the value of sys_member_vip.create_time
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_vip.create_time
     *
     * @param createTime the value for sys_member_vip.create_time
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}