package com.sys.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SysPetSymptoms implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_symptoms.pet_symptoms_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Long petSymptomsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_symptoms.pet_ill
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private String petIll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_symptoms.pet_type
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Integer petType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_symptoms.moneys
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private BigDecimal moneys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_symptoms.create_time
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_pet_symptoms
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_symptoms.pet_symptoms_id
     *
     * @return the value of sys_pet_symptoms.pet_symptoms_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Long getPetSymptomsId() {
        return petSymptomsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_symptoms.pet_symptoms_id
     *
     * @param petSymptomsId the value for sys_pet_symptoms.pet_symptoms_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setPetSymptomsId(Long petSymptomsId) {
        this.petSymptomsId = petSymptomsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_symptoms.pet_ill
     *
     * @return the value of sys_pet_symptoms.pet_ill
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public String getPetIll() {
        return petIll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_symptoms.pet_ill
     *
     * @param petIll the value for sys_pet_symptoms.pet_ill
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setPetIll(String petIll) {
        this.petIll = petIll == null ? null : petIll.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_symptoms.pet_type
     *
     * @return the value of sys_pet_symptoms.pet_type
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Integer getPetType() {
        return petType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_symptoms.pet_type
     *
     * @param petType the value for sys_pet_symptoms.pet_type
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setPetType(Integer petType) {
        this.petType = petType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_symptoms.moneys
     *
     * @return the value of sys_pet_symptoms.moneys
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public BigDecimal getMoneys() {
        return moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_symptoms.moneys
     *
     * @param moneys the value for sys_pet_symptoms.moneys
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setMoneys(BigDecimal moneys) {
        this.moneys = moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_symptoms.create_time
     *
     * @return the value of sys_pet_symptoms.create_time
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_symptoms.create_time
     *
     * @param createTime the value for sys_pet_symptoms.create_time
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}