package com.sys.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SysPetVaccineConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine_config.pet_vaccine_config_id
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private Long petVaccineConfigId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine_config.pet_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private Integer petType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine_config.name
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine_config.time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private Integer time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine_config.moneys
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private BigDecimal moneys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine_config.create_time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_pet_vaccine_config
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine_config.pet_vaccine_config_id
     *
     * @return the value of sys_pet_vaccine_config.pet_vaccine_config_id
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public Long getPetVaccineConfigId() {
        return petVaccineConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine_config.pet_vaccine_config_id
     *
     * @param petVaccineConfigId the value for sys_pet_vaccine_config.pet_vaccine_config_id
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setPetVaccineConfigId(Long petVaccineConfigId) {
        this.petVaccineConfigId = petVaccineConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine_config.pet_type
     *
     * @return the value of sys_pet_vaccine_config.pet_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public Integer getPetType() {
        return petType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine_config.pet_type
     *
     * @param petType the value for sys_pet_vaccine_config.pet_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setPetType(Integer petType) {
        this.petType = petType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine_config.name
     *
     * @return the value of sys_pet_vaccine_config.name
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine_config.name
     *
     * @param name the value for sys_pet_vaccine_config.name
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine_config.time
     *
     * @return the value of sys_pet_vaccine_config.time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine_config.time
     *
     * @param time the value for sys_pet_vaccine_config.time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine_config.moneys
     *
     * @return the value of sys_pet_vaccine_config.moneys
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public BigDecimal getMoneys() {
        return moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine_config.moneys
     *
     * @param moneys the value for sys_pet_vaccine_config.moneys
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setMoneys(BigDecimal moneys) {
        this.moneys = moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine_config.create_time
     *
     * @return the value of sys_pet_vaccine_config.create_time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine_config.create_time
     *
     * @param createTime the value for sys_pet_vaccine_config.create_time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    private Integer isSelect;

    public Integer getIsSelect() {
        return isSelect;
    }

    public void setIsSelect(Integer isSelect) {
        this.isSelect = isSelect;
    }

    private Integer isOver;

    public Integer getIsOver() {
        return isOver;
    }

    public void setIsOver(Integer isOver) {
        this.isOver = isOver;
    }
}