package com.sys.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SysPetShowerTime implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower_time.pet_shower_time_id
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private Long petShowerTimeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower_time.pet_type
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private Integer petType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower_time.min_kg
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private Integer minKg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower_time.max_kg
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private Integer maxKg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower_time.time
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private Integer time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower_time.create_time
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private Date createTime;

    private BigDecimal baseMoneys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_pet_shower_time
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower_time.pet_shower_time_id
     *
     * @return the value of sys_pet_shower_time.pet_shower_time_id
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public Long getPetShowerTimeId() {
        return petShowerTimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower_time.pet_shower_time_id
     *
     * @param petShowerTimeId the value for sys_pet_shower_time.pet_shower_time_id
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setPetShowerTimeId(Long petShowerTimeId) {
        this.petShowerTimeId = petShowerTimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower_time.pet_type
     *
     * @return the value of sys_pet_shower_time.pet_type
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public Integer getPetType() {
        return petType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower_time.pet_type
     *
     * @param petType the value for sys_pet_shower_time.pet_type
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setPetType(Integer petType) {
        this.petType = petType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower_time.min_kg
     *
     * @return the value of sys_pet_shower_time.min_kg
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public Integer getMinKg() {
        return minKg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower_time.min_kg
     *
     * @param minKg the value for sys_pet_shower_time.min_kg
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setMinKg(Integer minKg) {
        this.minKg = minKg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower_time.max_kg
     *
     * @return the value of sys_pet_shower_time.max_kg
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public Integer getMaxKg() {
        return maxKg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower_time.max_kg
     *
     * @param maxKg the value for sys_pet_shower_time.max_kg
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setMaxKg(Integer maxKg) {
        this.maxKg = maxKg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower_time.time
     *
     * @return the value of sys_pet_shower_time.time
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower_time.time
     *
     * @param time the value for sys_pet_shower_time.time
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower_time.create_time
     *
     * @return the value of sys_pet_shower_time.create_time
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower_time.create_time
     *
     * @param createTime the value for sys_pet_shower_time.create_time
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public BigDecimal getBaseMoneys() {
        return baseMoneys;
    }

    public void setBaseMoneys(BigDecimal baseMoneys) {
        this.baseMoneys = baseMoneys;
    }
}