package com.sys.entity;

import java.io.Serializable;
import java.util.Date;

public class SysPetVaccineLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine_log.vaccine_log_id
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    private Long vaccineLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine_log.pet_id
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    private Long petId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine_log.pet_vaccine_config_id
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    private Long petVaccineConfigId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine_log.create_time
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_pet_vaccine_log
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine_log.vaccine_log_id
     *
     * @return the value of sys_pet_vaccine_log.vaccine_log_id
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    public Long getVaccineLogId() {
        return vaccineLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine_log.vaccine_log_id
     *
     * @param vaccineLogId the value for sys_pet_vaccine_log.vaccine_log_id
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    public void setVaccineLogId(Long vaccineLogId) {
        this.vaccineLogId = vaccineLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine_log.pet_id
     *
     * @return the value of sys_pet_vaccine_log.pet_id
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    public Long getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine_log.pet_id
     *
     * @param petId the value for sys_pet_vaccine_log.pet_id
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    public void setPetId(Long petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine_log.pet_vaccine_config_id
     *
     * @return the value of sys_pet_vaccine_log.pet_vaccine_config_id
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    public Long getPetVaccineConfigId() {
        return petVaccineConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine_log.pet_vaccine_config_id
     *
     * @param petVaccineConfigId the value for sys_pet_vaccine_log.pet_vaccine_config_id
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    public void setPetVaccineConfigId(Long petVaccineConfigId) {
        this.petVaccineConfigId = petVaccineConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine_log.create_time
     *
     * @return the value of sys_pet_vaccine_log.create_time
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine_log.create_time
     *
     * @param createTime the value for sys_pet_vaccine_log.create_time
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}