package com.sys.dao;

import com.sys.entity.SysMember;

public interface SysMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    int insert(SysMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    int insertSelective(SysMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    SysMember selectByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SysMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    int updateByPrimaryKey(SysMember record);

    SysMember selectMemberByAccount(String account);
}