package com.sys.dao;

import com.sys.entity.SysNotify;

import java.util.List;

public interface SysNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notify
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long notifyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notify
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    int insert(SysNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notify
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    int insertSelective(SysNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notify
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    SysNotify selectByPrimaryKey(Long notifyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notify
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SysNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_notify
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    int updateByPrimaryKey(SysNotify record);

    List<SysNotify> selectByMemberId(Long memberId);
}