package com.sys.dao;

import com.sys.entity.SysPetShop;

public interface SysPetShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shop
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long petShopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shop
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int insert(SysPetShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shop
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int insertSelective(SysPetShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shop
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    SysPetShop selectByPrimaryKey(Long petShopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shop
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SysPetShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shop
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int updateByPrimaryKey(SysPetShop record);
}