package com.sys.dao;

import com.sys.entity.SysPetShower;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysPetShowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long petShowerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    int insert(SysPetShower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    int insertSelective(SysPetShower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    SysPetShower selectByPrimaryKey(Long petShowerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SysPetShower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    int updateByPrimaryKey(SysPetShower record);

    List<SysPetShower> selectList(@Param("where") String where);
}