package com.sys.dao;

import com.sys.entity.SysPetVaccine;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysPetVaccineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long petVaccineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int insert(SysPetVaccine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int insertSelective(SysPetVaccine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    SysPetVaccine selectByPrimaryKey(Long petVaccineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SysPetVaccine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int updateByPrimaryKey(SysPetVaccine record);

    List<SysPetVaccine> selectList(@Param("where") String where);
}