package com.sys.dao;

import com.sys.entity.SysPetRechargeOrder;

public interface SysPetRechargeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_recharge_order
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long petRechargeOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_recharge_order
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int insert(SysPetRechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_recharge_order
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int insertSelective(SysPetRechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_recharge_order
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    SysPetRechargeOrder selectByPrimaryKey(Long petRechargeOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_recharge_order
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SysPetRechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_recharge_order
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    int updateByPrimaryKey(SysPetRechargeOrder record);
}