package com.sys.dao;

import com.sys.entity.SysPetShowerType;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysPetShowerTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long petShowerTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int insert(SysPetShowerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int insertSelective(SysPetShowerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    SysPetShowerType selectByPrimaryKey(Long petShowerTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SysPetShowerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_shower_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    int updateByPrimaryKey(SysPetShowerType record);

    List<SysPetShowerType> selectList(@Param("where") String where);
}