package com.sys.dao;

import com.sys.entity.SysPetSterilization;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysPetSterilizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_sterilization
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long petSterilizationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_sterilization
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    int insert(SysPetSterilization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_sterilization
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    int insertSelective(SysPetSterilization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_sterilization
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    SysPetSterilization selectByPrimaryKey(Long petSterilizationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_sterilization
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SysPetSterilization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_sterilization
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    int updateByPrimaryKey(SysPetSterilization record);

    List<SysPetSterilization> selectList(@Param("where") String where);
}