package com.sys.dao;

import com.sys.entity.SysPetVaccineLog;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysPetVaccineLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine_log
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long vaccineLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine_log
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    int insert(SysPetVaccineLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine_log
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    int insertSelective(SysPetVaccineLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine_log
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    SysPetVaccineLog selectByPrimaryKey(Long vaccineLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine_log
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(SysPetVaccineLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pet_vaccine_log
     *
     * @mbg.generated Tue May 24 00:21:00 GMT+08:00 2022
     */
    int updateByPrimaryKey(SysPetVaccineLog record);

    List<SysPetVaccineLog> selectList(@Param("where") String where);
}