package com.example.petclient.base.entry;

import java.io.Serializable;
import java.util.Date;

public class SysNotify implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notify.notify_id
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    private Long notifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notify.member_id
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notify.type
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notify.key_id
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    private Long keyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notify.title
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notify.message
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notify.status
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_notify.create_time
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_notify
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notify.notify_id
     *
     * @return the value of sys_notify.notify_id
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    public Long getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notify.notify_id
     *
     * @param notifyId the value for sys_notify.notify_id
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    public void setNotifyId(Long notifyId) {
        this.notifyId = notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notify.member_id
     *
     * @return the value of sys_notify.member_id
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notify.member_id
     *
     * @param memberId the value for sys_notify.member_id
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notify.type
     *
     * @return the value of sys_notify.type
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notify.type
     *
     * @param type the value for sys_notify.type
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notify.key_id
     *
     * @return the value of sys_notify.key_id
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    public Long getKeyId() {
        return keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notify.key_id
     *
     * @param keyId the value for sys_notify.key_id
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    public void setKeyId(Long keyId) {
        this.keyId = keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notify.title
     *
     * @return the value of sys_notify.title
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notify.title
     *
     * @param title the value for sys_notify.title
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notify.message
     *
     * @return the value of sys_notify.message
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notify.message
     *
     * @param message the value for sys_notify.message
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notify.status
     *
     * @return the value of sys_notify.status
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notify.status
     *
     * @param status the value for sys_notify.status
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notify.create_time
     *
     * @return the value of sys_notify.create_time
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notify.create_time
     *
     * @param createTime the value for sys_notify.create_time
     *
     * @mbg.generated Tue Apr 26 12:01:32 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}