package com.example.petclient.base.entry;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SysPetShower implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower.pet_shower_id
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private Long petShowerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower.pet_id
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private Long petId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower.pet_showe_type
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private String petShoweType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower.is_over
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private Integer isOver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower.is_notify
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private Integer isNotify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower.moneys
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private BigDecimal moneys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower.status
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower.create_time
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_pet_shower
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower.pet_shower_id
     *
     * @return the value of sys_pet_shower.pet_shower_id
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public Long getPetShowerId() {
        return petShowerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower.pet_shower_id
     *
     * @param petShowerId the value for sys_pet_shower.pet_shower_id
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setPetShowerId(Long petShowerId) {
        this.petShowerId = petShowerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower.pet_id
     *
     * @return the value of sys_pet_shower.pet_id
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public Long getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower.pet_id
     *
     * @param petId the value for sys_pet_shower.pet_id
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setPetId(Long petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower.pet_showe_type
     *
     * @return the value of sys_pet_shower.pet_showe_type
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public String getPetShoweType() {
        return petShoweType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower.pet_showe_type
     *
     * @param petShoweType the value for sys_pet_shower.pet_showe_type
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setPetShoweType(String petShoweType) {
        this.petShoweType = petShoweType == null ? null : petShoweType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower.is_over
     *
     * @return the value of sys_pet_shower.is_over
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public Integer getIsOver() {
        return isOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower.is_over
     *
     * @param isOver the value for sys_pet_shower.is_over
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setIsOver(Integer isOver) {
        this.isOver = isOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower.is_notify
     *
     * @return the value of sys_pet_shower.is_notify
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public Integer getIsNotify() {
        return isNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower.is_notify
     *
     * @param isNotify the value for sys_pet_shower.is_notify
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setIsNotify(Integer isNotify) {
        this.isNotify = isNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower.moneys
     *
     * @return the value of sys_pet_shower.moneys
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public BigDecimal getMoneys() {
        return moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower.moneys
     *
     * @param moneys the value for sys_pet_shower.moneys
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setMoneys(BigDecimal moneys) {
        this.moneys = moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower.status
     *
     * @return the value of sys_pet_shower.status
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower.status
     *
     * @param status the value for sys_pet_shower.status
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower.create_time
     *
     * @return the value of sys_pet_shower.create_time
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower.create_time
     *
     * @param createTime the value for sys_pet_shower.create_time
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    private String petName;

    private String userName;

    private String account;

    public String getPetName() {
        return petName;
    }

    public void setPetName(String petName) {
        this.petName = petName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    private String time;

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }
}