package com.example.petclient.base.entry;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SysPetShowerType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower_type.pet_shower_type_id
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private Long petShowerTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower_type.pet_shower_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private String petShowerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower_type.pet_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private Integer petType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower_type.moneys
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private BigDecimal moneys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower_type.create_time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower_type.show_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private Integer showType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shower_type.image
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_pet_shower_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower_type.pet_shower_type_id
     *
     * @return the value of sys_pet_shower_type.pet_shower_type_id
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public Long getPetShowerTypeId() {
        return petShowerTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower_type.pet_shower_type_id
     *
     * @param petShowerTypeId the value for sys_pet_shower_type.pet_shower_type_id
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setPetShowerTypeId(Long petShowerTypeId) {
        this.petShowerTypeId = petShowerTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower_type.pet_shower_type
     *
     * @return the value of sys_pet_shower_type.pet_shower_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public String getPetShowerType() {
        return petShowerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower_type.pet_shower_type
     *
     * @param petShowerType the value for sys_pet_shower_type.pet_shower_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setPetShowerType(String petShowerType) {
        this.petShowerType = petShowerType == null ? null : petShowerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower_type.pet_type
     *
     * @return the value of sys_pet_shower_type.pet_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public Integer getPetType() {
        return petType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower_type.pet_type
     *
     * @param petType the value for sys_pet_shower_type.pet_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setPetType(Integer petType) {
        this.petType = petType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower_type.moneys
     *
     * @return the value of sys_pet_shower_type.moneys
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public BigDecimal getMoneys() {
        return moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower_type.moneys
     *
     * @param moneys the value for sys_pet_shower_type.moneys
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setMoneys(BigDecimal moneys) {
        this.moneys = moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower_type.create_time
     *
     * @return the value of sys_pet_shower_type.create_time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower_type.create_time
     *
     * @param createTime the value for sys_pet_shower_type.create_time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower_type.show_type
     *
     * @return the value of sys_pet_shower_type.show_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public Integer getShowType() {
        return showType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower_type.show_type
     *
     * @param showType the value for sys_pet_shower_type.show_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setShowType(Integer showType) {
        this.showType = showType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shower_type.image
     *
     * @return the value of sys_pet_shower_type.image
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shower_type.image
     *
     * @param image the value for sys_pet_shower_type.image
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }
}