package com.example.petclient.base.entry;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SysPetSterilizationConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_sterilization_config.pet_sterilization_config_id
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private Long petSterilizationConfigId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_sterilization_config.pet_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private Integer petType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_sterilization_config.moneys
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private BigDecimal moneys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_sterilization_config.time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private Integer time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_sterilization_config.create_time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_pet_sterilization_config
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_sterilization_config.pet_sterilization_config_id
     *
     * @return the value of sys_pet_sterilization_config.pet_sterilization_config_id
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public Long getPetSterilizationConfigId() {
        return petSterilizationConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_sterilization_config.pet_sterilization_config_id
     *
     * @param petSterilizationConfigId the value for sys_pet_sterilization_config.pet_sterilization_config_id
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setPetSterilizationConfigId(Long petSterilizationConfigId) {
        this.petSterilizationConfigId = petSterilizationConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_sterilization_config.pet_type
     *
     * @return the value of sys_pet_sterilization_config.pet_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public Integer getPetType() {
        return petType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_sterilization_config.pet_type
     *
     * @param petType the value for sys_pet_sterilization_config.pet_type
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setPetType(Integer petType) {
        this.petType = petType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_sterilization_config.moneys
     *
     * @return the value of sys_pet_sterilization_config.moneys
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public BigDecimal getMoneys() {
        return moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_sterilization_config.moneys
     *
     * @param moneys the value for sys_pet_sterilization_config.moneys
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setMoneys(BigDecimal moneys) {
        this.moneys = moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_sterilization_config.time
     *
     * @return the value of sys_pet_sterilization_config.time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_sterilization_config.time
     *
     * @param time the value for sys_pet_sterilization_config.time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_sterilization_config.create_time
     *
     * @return the value of sys_pet_sterilization_config.create_time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_sterilization_config.create_time
     *
     * @param createTime the value for sys_pet_sterilization_config.create_time
     *
     * @mbg.generated Thu May 19 11:22:49 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}