package com.example.petclient.base.entry;

import java.io.Serializable;
import java.util.Date;

public class SysPetTest implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_test.pet_test_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private Long petTestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_test.pet_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private Long petId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_test.is_over
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private Integer isOver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_test.is_notify
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private Integer isNotify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_test.create_time
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_test.test_ill
     *
     * @mbg.generated Thu May 19 11:43:29 GMT+08:00 2022
     */
    private Long testIll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_test.status
     *
     * @mbg.generated Thu May 19 11:43:29 GMT+08:00 2022
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_pet_test
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_test.pet_test_id
     *
     * @return the value of sys_pet_test.pet_test_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public Long getPetTestId() {
        return petTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_test.pet_test_id
     *
     * @param petTestId the value for sys_pet_test.pet_test_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setPetTestId(Long petTestId) {
        this.petTestId = petTestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_test.pet_id
     *
     * @return the value of sys_pet_test.pet_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public Long getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_test.pet_id
     *
     * @param petId the value for sys_pet_test.pet_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setPetId(Long petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_test.is_over
     *
     * @return the value of sys_pet_test.is_over
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public Integer getIsOver() {
        return isOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_test.is_over
     *
     * @param isOver the value for sys_pet_test.is_over
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setIsOver(Integer isOver) {
        this.isOver = isOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_test.is_notify
     *
     * @return the value of sys_pet_test.is_notify
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public Integer getIsNotify() {
        return isNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_test.is_notify
     *
     * @param isNotify the value for sys_pet_test.is_notify
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setIsNotify(Integer isNotify) {
        this.isNotify = isNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_test.create_time
     *
     * @return the value of sys_pet_test.create_time
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_test.create_time
     *
     * @param createTime the value for sys_pet_test.create_time
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    private String userName;

    private String petName;

    private String account;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPetName() {
        return petName;
    }

    public void setPetName(String petName) {
        this.petName = petName;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_test.test_ill
     *
     * @return the value of sys_pet_test.test_ill
     *
     * @mbg.generated Thu May 19 11:43:29 GMT+08:00 2022
     */
    public Long getTestIll() {
        return testIll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_test.test_ill
     *
     * @param testIll the value for sys_pet_test.test_ill
     *
     * @mbg.generated Thu May 19 11:43:29 GMT+08:00 2022
     */
    public void setTestIll(Long testIll) {
        this.testIll = testIll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_test.status
     *
     * @return the value of sys_pet_test.status
     *
     * @mbg.generated Thu May 19 11:43:29 GMT+08:00 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_test.status
     *
     * @param status the value for sys_pet_test.status
     *
     * @mbg.generated Thu May 19 11:43:29 GMT+08:00 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }


    private String illName;

    public String getIllName() {
        return illName;
    }

    public void setIllName(String illName) {
        this.illName = illName;
    }
}