package com.example.petclient.base.entry;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SysPetOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_order.pet_order_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Long petOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_order.order_code
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private String orderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_order.pet_shop_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Long petShopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_order.moneys
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private BigDecimal moneys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_order.member_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_order.status
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_order.create_time
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Date createTime;

    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_pet_order
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_order.pet_order_id
     *
     * @return the value of sys_pet_order.pet_order_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Long getPetOrderId() {
        return petOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_order.pet_order_id
     *
     * @param petOrderId the value for sys_pet_order.pet_order_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setPetOrderId(Long petOrderId) {
        this.petOrderId = petOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_order.order_code
     *
     * @return the value of sys_pet_order.order_code
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_order.order_code
     *
     * @param orderCode the value for sys_pet_order.order_code
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_order.pet_shop_id
     *
     * @return the value of sys_pet_order.pet_shop_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Long getPetShopId() {
        return petShopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_order.pet_shop_id
     *
     * @param petShopId the value for sys_pet_order.pet_shop_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setPetShopId(Long petShopId) {
        this.petShopId = petShopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_order.moneys
     *
     * @return the value of sys_pet_order.moneys
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public BigDecimal getMoneys() {
        return moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_order.moneys
     *
     * @param moneys the value for sys_pet_order.moneys
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setMoneys(BigDecimal moneys) {
        this.moneys = moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_order.member_id
     *
     * @return the value of sys_pet_order.member_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_order.member_id
     *
     * @param memberId the value for sys_pet_order.member_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_order.status
     *
     * @return the value of sys_pet_order.status
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_order.status
     *
     * @param status the value for sys_pet_order.status
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_order.create_time
     *
     * @return the value of sys_pet_order.create_time
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_order.create_time
     *
     * @param createTime the value for sys_pet_order.create_time
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    private String account;

    private String userName;

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getShopName() {
        return shopName;
    }

    public void setShopName(String shopName) {
        this.shopName = shopName;
    }
}