package com.example.petclient.base.entry;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SysMember implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.member_id
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.account
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.password
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.user_name
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.phone
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.create_time
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.moneys
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    private BigDecimal moneys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.member_vip
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    private Long memberVip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_member
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.member_id
     *
     * @return the value of sys_member.member_id
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.member_id
     *
     * @param memberId the value for sys_member.member_id
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.account
     *
     * @return the value of sys_member.account
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.account
     *
     * @param account the value for sys_member.account
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.password
     *
     * @return the value of sys_member.password
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.password
     *
     * @param password the value for sys_member.password
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.user_name
     *
     * @return the value of sys_member.user_name
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.user_name
     *
     * @param userName the value for sys_member.user_name
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.phone
     *
     * @return the value of sys_member.phone
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.phone
     *
     * @param phone the value for sys_member.phone
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.create_time
     *
     * @return the value of sys_member.create_time
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.create_time
     *
     * @param createTime the value for sys_member.create_time
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.moneys
     *
     * @return the value of sys_member.moneys
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public BigDecimal getMoneys() {
        return moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.moneys
     *
     * @param moneys the value for sys_member.moneys
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public void setMoneys(BigDecimal moneys) {
        this.moneys = moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.member_vip
     *
     * @return the value of sys_member.member_vip
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public Long getMemberVip() {
        return memberVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.member_vip
     *
     * @param memberVip the value for sys_member.member_vip
     *
     * @mbg.generated Thu May 19 10:43:29 GMT+08:00 2022
     */
    public void setMemberVip(Long memberVip) {
        this.memberVip = memberVip;
    }

    private String vipName;

    public String getVipName() {
        return vipName;
    }

    public void setVipName(String vipName) {
        this.vipName = vipName;
    }
}