package com.example.petclient.base.entry;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SysPetShop implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shop.pet_shop_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Long petShopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shop.shop_name
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shop.pet_type
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Integer petType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shop.moneys
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private BigDecimal moneys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shop.image
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_shop.create_time
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_pet_shop
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shop.pet_shop_id
     *
     * @return the value of sys_pet_shop.pet_shop_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Long getPetShopId() {
        return petShopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shop.pet_shop_id
     *
     * @param petShopId the value for sys_pet_shop.pet_shop_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setPetShopId(Long petShopId) {
        this.petShopId = petShopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shop.shop_name
     *
     * @return the value of sys_pet_shop.shop_name
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shop.shop_name
     *
     * @param shopName the value for sys_pet_shop.shop_name
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shop.pet_type
     *
     * @return the value of sys_pet_shop.pet_type
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Integer getPetType() {
        return petType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shop.pet_type
     *
     * @param petType the value for sys_pet_shop.pet_type
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setPetType(Integer petType) {
        this.petType = petType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shop.moneys
     *
     * @return the value of sys_pet_shop.moneys
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public BigDecimal getMoneys() {
        return moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shop.moneys
     *
     * @param moneys the value for sys_pet_shop.moneys
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setMoneys(BigDecimal moneys) {
        this.moneys = moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shop.image
     *
     * @return the value of sys_pet_shop.image
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shop.image
     *
     * @param image the value for sys_pet_shop.image
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_shop.create_time
     *
     * @return the value of sys_pet_shop.create_time
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_shop.create_time
     *
     * @param createTime the value for sys_pet_shop.create_time
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}