package com.example.petclient.base.entry;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SysPetVaccine implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine.pet_vaccine_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Long petVaccineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine.pet_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Long petId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine.pet_vaccine_config_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Long petVaccineConfigId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine.moneys
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private BigDecimal moneys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine.status
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine.is_over
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Integer isOver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine.is_notify
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Integer isNotify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_vaccine.create_time
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_pet_vaccine
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine.pet_vaccine_id
     *
     * @return the value of sys_pet_vaccine.pet_vaccine_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Long getPetVaccineId() {
        return petVaccineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine.pet_vaccine_id
     *
     * @param petVaccineId the value for sys_pet_vaccine.pet_vaccine_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setPetVaccineId(Long petVaccineId) {
        this.petVaccineId = petVaccineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine.pet_id
     *
     * @return the value of sys_pet_vaccine.pet_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Long getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine.pet_id
     *
     * @param petId the value for sys_pet_vaccine.pet_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setPetId(Long petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine.pet_vaccine_config_id
     *
     * @return the value of sys_pet_vaccine.pet_vaccine_config_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Long getPetVaccineConfigId() {
        return petVaccineConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine.pet_vaccine_config_id
     *
     * @param petVaccineConfigId the value for sys_pet_vaccine.pet_vaccine_config_id
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setPetVaccineConfigId(Long petVaccineConfigId) {
        this.petVaccineConfigId = petVaccineConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine.moneys
     *
     * @return the value of sys_pet_vaccine.moneys
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public BigDecimal getMoneys() {
        return moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine.moneys
     *
     * @param moneys the value for sys_pet_vaccine.moneys
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setMoneys(BigDecimal moneys) {
        this.moneys = moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine.status
     *
     * @return the value of sys_pet_vaccine.status
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine.status
     *
     * @param status the value for sys_pet_vaccine.status
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine.is_over
     *
     * @return the value of sys_pet_vaccine.is_over
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Integer getIsOver() {
        return isOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine.is_over
     *
     * @param isOver the value for sys_pet_vaccine.is_over
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setIsOver(Integer isOver) {
        this.isOver = isOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine.is_notify
     *
     * @return the value of sys_pet_vaccine.is_notify
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Integer getIsNotify() {
        return isNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine.is_notify
     *
     * @param isNotify the value for sys_pet_vaccine.is_notify
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setIsNotify(Integer isNotify) {
        this.isNotify = isNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_vaccine.create_time
     *
     * @return the value of sys_pet_vaccine.create_time
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_vaccine.create_time
     *
     * @param createTime the value for sys_pet_vaccine.create_time
     *
     * @mbg.generated Mon May 23 15:44:07 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    private String petName;

    private String userName;

    private String account;

    private String vaccineName;

    public String getPetName() {
        return petName;
    }

    public void setPetName(String petName) {
        this.petName = petName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getVaccineName() {
        return vaccineName;
    }

    public void setVaccineName(String vaccineName) {
        this.vaccineName = vaccineName;
    }
}