package com.example.petclient.base.entry;

import java.io.Serializable;
import java.util.Date;

public class SysPet implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet.pet_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private Long petId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet.pet_name
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private String petName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet.pet_type
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private String petType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet.pet_info
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private String petInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet.pet_age
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private String petAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet.pet_color
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private String petColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet.pet_detail
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private String petDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet.member_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet.gps_info
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private String gpsInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet.create_time
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet.weight
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet.is_sterilization
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private Integer isSterilization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_pet
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet.pet_id
     *
     * @return the value of sys_pet.pet_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public Long getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet.pet_id
     *
     * @param petId the value for sys_pet.pet_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setPetId(Long petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet.pet_name
     *
     * @return the value of sys_pet.pet_name
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public String getPetName() {
        return petName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet.pet_name
     *
     * @param petName the value for sys_pet.pet_name
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setPetName(String petName) {
        this.petName = petName == null ? null : petName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet.pet_type
     *
     * @return the value of sys_pet.pet_type
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public String getPetType() {
        return petType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet.pet_type
     *
     * @param petType the value for sys_pet.pet_type
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setPetType(String petType) {
        this.petType = petType == null ? null : petType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet.pet_info
     *
     * @return the value of sys_pet.pet_info
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public String getPetInfo() {
        return petInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet.pet_info
     *
     * @param petInfo the value for sys_pet.pet_info
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setPetInfo(String petInfo) {
        this.petInfo = petInfo == null ? null : petInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet.pet_age
     *
     * @return the value of sys_pet.pet_age
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public String getPetAge() {
        return petAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet.pet_age
     *
     * @param petAge the value for sys_pet.pet_age
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setPetAge(String petAge) {
        this.petAge = petAge == null ? null : petAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet.pet_color
     *
     * @return the value of sys_pet.pet_color
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public String getPetColor() {
        return petColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet.pet_color
     *
     * @param petColor the value for sys_pet.pet_color
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setPetColor(String petColor) {
        this.petColor = petColor == null ? null : petColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet.pet_detail
     *
     * @return the value of sys_pet.pet_detail
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public String getPetDetail() {
        return petDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet.pet_detail
     *
     * @param petDetail the value for sys_pet.pet_detail
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setPetDetail(String petDetail) {
        this.petDetail = petDetail == null ? null : petDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet.member_id
     *
     * @return the value of sys_pet.member_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet.member_id
     *
     * @param memberId the value for sys_pet.member_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet.gps_info
     *
     * @return the value of sys_pet.gps_info
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public String getGpsInfo() {
        return gpsInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet.gps_info
     *
     * @param gpsInfo the value for sys_pet.gps_info
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setGpsInfo(String gpsInfo) {
        this.gpsInfo = gpsInfo == null ? null : gpsInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet.create_time
     *
     * @return the value of sys_pet.create_time
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet.create_time
     *
     * @param createTime the value for sys_pet.create_time
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    private String account;

    private String userName;

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet.weight
     *
     * @return the value of sys_pet.weight
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet.weight
     *
     * @param weight the value for sys_pet.weight
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet.is_sterilization
     *
     * @return the value of sys_pet.is_sterilization
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public Integer getIsSterilization() {
        return isSterilization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet.is_sterilization
     *
     * @param isSterilization the value for sys_pet.is_sterilization
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setIsSterilization(Integer isSterilization) {
        this.isSterilization = isSterilization;
    }
}