package com.example.petclient.base.entry;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SysPetIll implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_ill.pet_ill_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private Long petIllId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_ill.pet_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private Long petId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_ill.ill_detail
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private String illDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_ill.is_over
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private Integer isOver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_ill.is_notify
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private Integer isNotify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_ill.create_time
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_ill.status
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pet_ill.moneys
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    private BigDecimal moneys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_pet_ill
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_ill.pet_ill_id
     *
     * @return the value of sys_pet_ill.pet_ill_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public Long getPetIllId() {
        return petIllId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_ill.pet_ill_id
     *
     * @param petIllId the value for sys_pet_ill.pet_ill_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setPetIllId(Long petIllId) {
        this.petIllId = petIllId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_ill.pet_id
     *
     * @return the value of sys_pet_ill.pet_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public Long getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_ill.pet_id
     *
     * @param petId the value for sys_pet_ill.pet_id
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setPetId(Long petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_ill.ill_detail
     *
     * @return the value of sys_pet_ill.ill_detail
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public String getIllDetail() {
        return illDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_ill.ill_detail
     *
     * @param illDetail the value for sys_pet_ill.ill_detail
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setIllDetail(String illDetail) {
        this.illDetail = illDetail == null ? null : illDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_ill.is_over
     *
     * @return the value of sys_pet_ill.is_over
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public Integer getIsOver() {
        return isOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_ill.is_over
     *
     * @param isOver the value for sys_pet_ill.is_over
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setIsOver(Integer isOver) {
        this.isOver = isOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_ill.is_notify
     *
     * @return the value of sys_pet_ill.is_notify
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public Integer getIsNotify() {
        return isNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_ill.is_notify
     *
     * @param isNotify the value for sys_pet_ill.is_notify
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setIsNotify(Integer isNotify) {
        this.isNotify = isNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_ill.create_time
     *
     * @return the value of sys_pet_ill.create_time
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_ill.create_time
     *
     * @param createTime the value for sys_pet_ill.create_time
     *
     * @mbg.generated Sun Apr 10 15:41:31 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    private String userName;

    private String petName;

    private String account;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPetName() {
        return petName;
    }

    public void setPetName(String petName) {
        this.petName = petName;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_ill.status
     *
     * @return the value of sys_pet_ill.status
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_ill.status
     *
     * @param status the value for sys_pet_ill.status
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pet_ill.moneys
     *
     * @return the value of sys_pet_ill.moneys
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public BigDecimal getMoneys() {
        return moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pet_ill.moneys
     *
     * @param moneys the value for sys_pet_ill.moneys
     *
     * @mbg.generated Thu May 19 11:37:37 GMT+08:00 2022
     */
    public void setMoneys(BigDecimal moneys) {
        this.moneys = moneys;
    }
}